site_name: LF10c

strict: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - LS10c.1: LS1.md
    - LS10c.2: LS2.md
    - LS10c.3: LS3.md
    - LS10c.4: LS4.md
    - LS10c.5: LS5.md
    - LS10c.6: LS6.md
    - LS10c.7: LS7.md
    - LS10c.8: LS8.md
    - LS10c.9: LS9.md
